approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - samvaughn
  - berrynorth
  - atracy
  - mattrobbins
  - RyanColborne
  - nelson8862
  - AmandaWalter
  - jjonesoct
  - liapretorius
  - PhatKiwi
  - evanderlinden
  name: default
  required: 1
extends: ca-base
